@startuml

class キャラクター{
    名前
    HP

    + 戦う()
    + 逃げる()
}

class 人間{
    + 眠る()
}

class 魔法使い {
    魔力
    + 魔法()
}
class 勇者{
    + 座る()
}
class スライム{
    + 飲み込む()
}

キャラクター <|--人間
人間 <|--魔法使い
人間 <|--勇者
キャラクター <|---スライム

@enduml