@startuml
class BaseData{
    int id
    String name

    +createdAt()
    +updatedAt()
}

class Task{
    int categoryId
    boolean complete
    String memo

    +notice()
    +complete()
    +revive()
}

class Category {
    id userId

    +addTask()
    +sort()
}

class User{
    String eMain 
    String password

    +login()
    +logout()
    +addCategory()
    +editTask()
    +deleteTask()
    +deleteCategory()
    +passwordReset()
}



BaseData<|---- Category
BaseData<|-- User
BaseData<|---- Task

User "1" -- "1..*" Category
Category "1" -- "0..*" Task

@enduml