@startuml
class BaseData{
    int id
    String name

    +createdAt()
    +updatedAt()
}

class Task{
    boolean complete
    String memo
    int categoryId

    +notice()
    +complete()
    +revive()
    +create()
}

class Category {
    int userId

    +addTask()
    +create()
    +sort()
}

class User{
    String eMail
    String password

    +login()
    +logout()
    +deleteTask()
    +deleteCategory()
    +passwordReset()
}



BaseData<|---- Category
BaseData<|-- User
BaseData<|---- Task

User "1" -- "1..*" Category
Category "1" -- "0..*" Task

@enduml